// SPDX-License-Identifier: Apache-2.0
// Absorbs :engine and :runtime (Phase 5 module reorg).

import java.security.MessageDigest

plugins {
    id("jk.java-conventions")
}

description = "jk build engine: the Goal/Phase scheduler and the build pipeline, " +
        "run in-process by the CLI. Absorbs the former :engine and :runtime modules."

dependencies {
    implementation(project(":core"))
    implementation(project(":io"))
    implementation(project(":plugin-api"))
    implementation(project(":resolver"))
    implementation(project(":toolchain"))
    // ASM — used by the incremental Java compiler's dependency extraction
    implementation(libs.asm)
    implementation(libs.asm.tree)
    implementation(libs.asm.commons)

    testImplementation(libs.jgit)   // git test fixtures
}

// ---------------------------------------------------------------------------
// Worker SHA resources (absorbed from :runtime's build.gradle.kts).
// For each worker we hash its jar at build time and emit the hex digest as a
// classpath resource at /META-INF/jk-<artifact>-sha256.txt so WorkerJar can
// locate the jar in the CAS at runtime without knowing its path.
// Note: :host itself is NOT in this list (that would be circular); its sha
// resource is generated by :cli (see cli/build.gradle.kts).
val shaWorkerModules = listOf(
    ":kotlin-compiler", ":java-compiler", ":git-client",
    ":auditor", ":publisher", ":image-builder", ":compat-bridge",
)
val workerShaTasks = shaWorkerModules.map { path ->
    val artifact = "jk-" + path.removePrefix(":")
    val ident = artifact.replace("-", "")
    val cfg = configurations.create("${ident}Jar") {
        isCanBeConsumed = false
        isCanBeResolved = true
        isTransitive = false
    }
    dependencies.add(cfg.name, project(path))
    val outDir = "generated/resources/worker-sha/$artifact"
    val outFile = layout.buildDirectory.file("$outDir/META-INF/$artifact-sha256.txt")
    val task = tasks.register("write${ident}Sha") {
        inputs.files(cfg)
        outputs.file(outFile)
        doLast {
            val digest = MessageDigest.getInstance("SHA-256").digest(cfg.singleFile.readBytes())
            outFile.get().asFile.apply {
                parentFile.mkdirs()
                writeText(digest.joinToString("") { "%02x".format(it.toInt() and 0xff) })
            }
        }
    }
    sourceSets.named("main") { resources.srcDir(layout.buildDirectory.dir(outDir)) }
    task
}
tasks.named("processResources") { dependsOn(workerShaTasks) }
tasks.named("sourcesJar") { dependsOn(workerShaTasks) }

// ---------------------------------------------------------------------------
// Test-runner SHA resource (absorbed from :engine/build.gradle.kts).
// JUnitLauncher looks up jk-test-runner.jar in the CAS by its SHA-256.
val testRunnerJarCfg by configurations.creating {
    isCanBeConsumed = false
    isCanBeResolved = true
    isTransitive = false
}
dependencies {
    testRunnerJarCfg(project(":test-runner"))
}
val writeRunnerSha by tasks.registering {
    val inputJar = testRunnerJarCfg
    inputs.files(inputJar)
    val outFile = layout.buildDirectory.file(
            "generated/resources/runner-sha/META-INF/jk-test-runner-sha256.txt")
    outputs.file(outFile)
    doLast {
        val jarBytes = inputJar.singleFile.readBytes()
        val digest = MessageDigest.getInstance("SHA-256").digest(jarBytes)
        outFile.get().asFile.apply {
            parentFile.mkdirs()
            writeText(digest.joinToString("") { "%02x".format(it.toInt() and 0xff) })
        }
    }
}
sourceSets.named("main") {
    resources.srcDir(layout.buildDirectory.dir("generated/resources/runner-sha"))
}
tasks.named("processResources") { dependsOn(writeRunnerSha) }
tasks.named("sourcesJar") { dependsOn(writeRunnerSha) }

// ---------------------------------------------------------------------------
// Worker jar paths for tests (WorkerJavacTest, KotlinWorkerSetupTest, etc.)
val javaCompilerWorkerJar by configurations.creating {
    isCanBeConsumed = false; isCanBeResolved = true; isTransitive = false
}
dependencies { javaCompilerWorkerJar(project(":java-compiler")) }
tasks.withType<Test>().configureEach {
    dependsOn(javaCompilerWorkerJar, testRunnerJarCfg)
    doFirst {
        systemProperty("jk.java.worker.jar", javaCompilerWorkerJar.singleFile.absolutePath)
        systemProperty("jk.test.runner.jar", testRunnerJarCfg.singleFile.absolutePath)
    }
}

// Pass the git-client jar path to tests (GitFetcher forks it).
val testGitWorkerJar by configurations.creating {
    isCanBeConsumed = false; isCanBeResolved = true; isTransitive = false
}
dependencies { testGitWorkerJar(project(":git-client")) }
tasks.withType<Test>().configureEach {
    dependsOn(testGitWorkerJar)
    doFirst { systemProperty("jk.git-client.worker.jar", testGitWorkerJar.singleFile.absolutePath) }
}

