[project]
group    = "cc.jumpkick"
name     = "jk"
version  = "0.10.0-SNAPSHOT"
description = "A modern build tool for Java and Kotlin."
jdk      = 25
java     = 25

[workspace]
modules = ["shared/jk-api", "shared/plugin-sdk", "shared/core", "shared/client-io", "server/io", "server/resolver", "shared/toolchain-jdk", "server/toolchain", "shared/wire", "server/engine", "clients/cli", "clients/cli-engine"]
