[project]
group    = "dev.jkbuild"
artifact = "jk-engine"
version  = "0.6.0-SNAPSHOT"
jdk      = 25
java     = 25

[dependencies.main]
jk-core.workspace                 = true
jk-io.workspace                   = true
junit-jupiter.workspace           = true
junit-platform-launcher.workspace = true
asm                               = { group = "org.ow2.asm", version = "9.10" }
asm-tree                          = { group = "org.ow2.asm", version = "9.10" }

[dependencies.test]
assertj-core.workspace            = true
junit-platform-launcher.workspace = true
