// SPDX-License-Identifier: Apache-2.0
package dev.jkbuild.tool;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.nio.file.attribute.PosixFilePermission;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

/**
 * Writes a persistent launcher for {@code jk install} and runs the
 * ephemeral exec path for {@code jk exec} (PRD §20).
 *
 * <p>Persistent layout per PRD §20.2 (paths resolved by the caller via
 * {@code dev.jkbuild.util.JkDirs}):
 * <pre>
 *   $JK_STATE_DIR/tools/envs/&lt;bin&gt;/env.json   # metadata (XDG: ~/.local/state/jk/...)
 *   $JK_BIN_DIR/&lt;bin&gt;                          # launcher script  (XDG: ~/.local/bin/...)
 * </pre>
 *
 * <p>The launcher embeds an absolute classpath into the CAS — there's no
 * runtime lookup. A coord upgrade re-runs {@code jk install} which
 * regenerates both files.
 */
public final class ToolLauncher {

    private ToolLauncher() {}

    /**
     * Materialise {@code env} as an installed tool. Writes the launcher
     * script under {@code binDir} and the env metadata under
     * {@code envsRoot/<binName>/env.json}. Idempotent.
     *
     * @return the launcher path the user should add to PATH.
     */
    public static Path install(Path envsRoot, Path binDir, Path javaHome, ToolEnv env)
            throws IOException {
        Path envDir = envsRoot.resolve(env.binName());
        Files.createDirectories(envDir);
        Files.createDirectories(binDir);

        Files.writeString(envDir.resolve("env.json"), renderEnvJson(env, javaHome),
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING);

        Path launcher = binDir.resolve(env.binName() + (isWindows() ? ".cmd" : ""));
        String script = isWindows()
                ? renderWindowsLauncher(env, javaHome)
                : renderPosixLauncher(env, javaHome);
        Files.writeString(launcher, script, StandardCharsets.UTF_8,
                StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
        markExecutable(launcher);
        return launcher;
    }

    /**
     * Exec the env's main class in-process via {@link ProcessBuilder}
     * (the {@code jk exec} path). Returns the child's exit code.
     */
    public static int execEphemeral(Path javaHome, ToolEnv env, List<String> args)
            throws IOException, InterruptedException {
        List<String> cmd = new ArrayList<>();
        cmd.add(javaBinary(javaHome).toString());
        cmd.add("-cp");
        cmd.add(joinClasspath(env.classpath()));
        cmd.add(env.mainClass());
        cmd.addAll(args);
        return new ProcessBuilder(cmd).inheritIO().start().waitFor();
    }

    private static Path javaBinary(Path javaHome) {
        String exe = isWindows() ? "java.exe" : "java";
        return javaHome.resolve("bin").resolve(exe);
    }

    private static String joinClasspath(List<Path> classpath) {
        String sep = isWindows() ? ";" : ":";
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < classpath.size(); i++) {
            if (i > 0) sb.append(sep);
            sb.append(classpath.get(i).toAbsolutePath());
        }
        return sb.toString();
    }

    private static String renderPosixLauncher(ToolEnv env, Path javaHome) {
        StringBuilder sb = new StringBuilder();
        sb.append("#!/usr/bin/env bash\n");
        sb.append("# Generated by jk install — do not edit.\n");
        sb.append("# Re-run `jk install ").append(env.primary().toGav()).append("` to refresh.\n");
        sb.append("exec ").append(shellQuote(javaBinary(javaHome).toString())).append(" \\\n");
        sb.append("  -cp ").append(shellQuote(joinClasspath(env.classpath()))).append(" \\\n");
        sb.append("  ").append(env.mainClass()).append(" \"$@\"\n");
        return sb.toString();
    }

    private static String renderWindowsLauncher(ToolEnv env, Path javaHome) {
        StringBuilder sb = new StringBuilder();
        sb.append("@echo off\r\n");
        sb.append("REM Generated by jk install -- do not edit.\r\n");
        sb.append('"').append(javaBinary(javaHome)).append('"');
        sb.append(" -cp \"").append(joinClasspath(env.classpath())).append("\" ");
        sb.append(env.mainClass()).append(" %*\r\n");
        return sb.toString();
    }

    private static String renderEnvJson(ToolEnv env, Path javaHome) {
        StringBuilder sb = new StringBuilder();
        sb.append("{\n");
        sb.append("  \"binName\": ").append(jsonString(env.binName())).append(",\n");
        sb.append("  \"primary\": ").append(jsonString(env.primary().toGav())).append(",\n");
        sb.append("  \"mainClass\": ").append(jsonString(env.mainClass())).append(",\n");
        sb.append("  \"javaHome\": ").append(jsonString(javaHome.toAbsolutePath().toString())).append(",\n");
        sb.append("  \"classpath\": [\n");
        List<Path> cp = env.classpath();
        for (int i = 0; i < cp.size(); i++) {
            sb.append("    ").append(jsonString(cp.get(i).toAbsolutePath().toString()));
            if (i + 1 < cp.size()) sb.append(",");
            sb.append("\n");
        }
        sb.append("  ]\n");
        sb.append("}\n");
        return sb.toString();
    }

    private static String jsonString(String s) {
        StringBuilder sb = new StringBuilder(s.length() + 2);
        sb.append('"');
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '\\' -> sb.append("\\\\");
                case '"' -> sb.append("\\\"");
                case '\n' -> sb.append("\\n");
                case '\r' -> sb.append("\\r");
                case '\t' -> sb.append("\\t");
                default -> sb.append(c);
            }
        }
        sb.append('"');
        return sb.toString();
    }

    private static String shellQuote(String value) {
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (!(Character.isLetterOrDigit(c)
                    || c == '_' || c == '-' || c == '.' || c == '/' || c == ':')) {
                return "'" + value.replace("'", "'\\''") + "'";
            }
        }
        return value;
    }

    private static void markExecutable(Path file) {
        if (isWindows()) return;
        try {
            Set<PosixFilePermission> perms = EnumSet.copyOf(Files.getPosixFilePermissions(file));
            perms.add(PosixFilePermission.OWNER_EXECUTE);
            perms.add(PosixFilePermission.GROUP_EXECUTE);
            perms.add(PosixFilePermission.OTHERS_EXECUTE);
            Files.setPosixFilePermissions(file, perms);
        } catch (UnsupportedOperationException | IOException ignored) {
            // Non-POSIX filesystem — caller is on Windows or an exotic FS.
        }
    }

    private static boolean isWindows() {
        return System.getProperty("os.name", "").toLowerCase(Locale.ROOT).contains("win");
    }
}
