[project]
group    = "dev.jkbuild"
artifact = "jk-io"
version  = "0.6.0-SNAPSHOT"
jdk      = 25
java     = 25

[dependencies.main]
jk-core.workspace          = true
jgit                       = { group = "org.eclipse.jgit", artifact = "org.eclipse.jgit", version = "7.6.0.202603022253-r" }
jackson-databind.workspace = true

[dependencies.test]
assertj-core.workspace            = true
junit-jupiter.workspace           = true
junit-platform-launcher.workspace = true
