// SPDX-License-Identifier: Apache-2.0

import java.security.MessageDigest

plugins {
    id("jk.java-conventions")
}

description = "jk runtime: the build pipeline + command logic, embeddable without the CLI/TUI"

dependencies {
    implementation(project(":core"))
    implementation(project(":io"))
    // The shared NDJSON codec (GitFetcher reads worker output with it). engine's
    // dependency on plugin-api is `implementation`, so it isn't exposed here.
    implementation(project(":plugin-api"))
    implementation(project(":resolver"))
    implementation(project(":engine"))
    implementation(project(":toolchain"))
    implementation(project(":compat"))
    implementation(project(":supply-chain"))
    testImplementation(libs.jgit)   // test fixtures only; not in production binary
}

// The worker jars aren't embedded — they're separate processes that runtime
// locates in the local CAS by content SHA-256 (the uniform on-disk location that
// works for both JVM and native-image jk; `jk sync` / `:<worker>:installLocalCas`
// populate it). dev.jkbuild.worker.WorkerJar needs the expected hash at runtime,
// so for each worker we hash its jar at build time and emit the hex digest as a
// resource at /META-INF/jk-<artifact>-sha256.txt. (test-runner's sha is emitted
// by :engine, where JUnitLauncher locates that worker.)
// Note: :host is NOT in this list because :host depends on :runtime, creating
// a circular dependency if runtime tried to hash it. The jk-host sha resource
// is generated by :cli instead (see cli/build.gradle.kts).
val shaWorkerModules = listOf(
    ":kotlin-compiler", ":java-compiler", ":git-runner",
    ":audit-runner", ":publish-runner", ":image-runner", ":compat-runner",
)
val workerShaTasks = shaWorkerModules.map { path ->
    val artifact = "jk-" + path.removePrefix(":")    // e.g. jk-kotlin-compiler
    val ident = artifact.replace("-", "")            // safe task/config identifier
    val cfg = configurations.create("${ident}Jar") {
        isCanBeConsumed = false
        isCanBeResolved = true
        isTransitive = false
    }
    dependencies.add(cfg.name, project(path))
    val outDir = "generated/resources/worker-sha/$artifact"
    val outFile = layout.buildDirectory.file("$outDir/META-INF/$artifact-sha256.txt")
    val task = tasks.register("write${ident}Sha") {
        inputs.files(cfg)            // carries the dependency on the worker's jar task
        outputs.file(outFile)
        doLast {
            val digest = MessageDigest.getInstance("SHA-256").digest(cfg.singleFile.readBytes())
            outFile.get().asFile.apply {
                parentFile.mkdirs()
                writeText(digest.joinToString("") { "%02x".format(it.toInt() and 0xff) })
            }
        }
    }
    sourceSets.named("main") { resources.srcDir(layout.buildDirectory.dir(outDir)) }
    task
}
// sourcesJar (from withSourcesJar()) bundles the main resource srcDirs, so it
// reads these generated dirs too — Gradle 9 rejects undeclared task→task flow,
// so wire both consumers explicitly.
tasks.named("processResources") { dependsOn(workerShaTasks) }
tasks.named("sourcesJar") { dependsOn(workerShaTasks) }

// Pass the git-runner jar path to tests so GitFetcher can fork the worker.
val testGitWorkerJar by configurations.creating {
    isCanBeConsumed = false; isCanBeResolved = true; isTransitive = false
}
dependencies { testGitWorkerJar(project(":git-runner")) }
tasks.withType<Test>().configureEach {
    dependsOn(testGitWorkerJar)
    doFirst { systemProperty("jk.git.worker.jar", testGitWorkerJar.singleFile.absolutePath) }
}
