// SPDX-License-Identifier: Apache-2.0
package dev.jkbuild.command;

import dev.jkbuild.cache.Cas;
import dev.jkbuild.cli.GlobalOptions;
import dev.jkbuild.cli.theme.Theme;
import dev.jkbuild.config.JkBuildParser;
import dev.jkbuild.config.WorkspaceClasspath;
import dev.jkbuild.config.WorkspaceLoader;
import dev.jkbuild.config.WorkspaceLocator;
import dev.jkbuild.http.Http;
import dev.jkbuild.jdk.IntellijJdkDir;
import dev.jkbuild.model.Coordinate;
import dev.jkbuild.repo.JkMavenLocalRepo;
import dev.jkbuild.repo.MavenLayout;
import dev.jkbuild.jdk.IntellijSdkRegistrar;
import dev.jkbuild.jdk.JdkHit;
import dev.jkbuild.jdk.JdkRegistry;
import dev.jkbuild.jdk.JdkSelector;
import dev.jkbuild.jdk.JdkVendor;
import dev.jkbuild.jdk.StableJdkPointer;
import dev.jkbuild.layout.BuildLayout;
import dev.jkbuild.lock.Lockfile;
import dev.jkbuild.lock.LockfileReader;
import dev.jkbuild.model.JkBuild;
import dev.jkbuild.model.Dependency;
import dev.jkbuild.model.Scope;
import dev.jkbuild.runtime.BuildGraph;
import dev.jkbuild.model.command.CliCommand;
import dev.jkbuild.model.command.Invocation;
import dev.jkbuild.model.command.Opt;
import dev.jkbuild.resolver.CacheSync;
import dev.jkbuild.util.JkDirs;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Optional;
import java.util.Set;

/**
 * {@code jk idea} — generate IntelliJ IDEA project files ({@code .idea/} +
 * {@code *.iml}) for a workspace or single project.
 *
 * <p>Generated files:
 * <ul>
 *   <li>{@code .idea/modules.xml} — module registry</li>
 *   <li>{@code .idea/misc.xml} — project SDK + language level</li>
 *   <li>{@code .idea/compiler.xml} — per-module bytecode target + annotation
 *       processing profiles</li>
 *   <li>{@code .idea/libraries/*.xml} — one per external dependency;
 *       sources JARs attached when {@code sources-checksum} is in the lock</li>
 *   <li>{@code .idea/runConfigurations/*.xml} — for members with a
 *       {@code [project] main} class</li>
 *   <li>{@code <member>/<module>.iml} — per module: source roots, deps,
 *       scope; workspace siblings become module references</li>
 * </ul>
 *
 * <p>Each module maps to a stable {@code jk-<vendor>-<level>} SDK (e.g.
 * {@code jk-temurin-25}) backed by a {@link StableJdkPointer} path and
 * registered into the IDEs' global {@code jdk.table.xml} (best-effort — a
 * running IDE may clobber the edit on exit, so re-run with it closed). The
 * stable path means jk's point-release JDK upgrades stay transparent to the IDE.
 *
 * <p>Existing files the command generates are overwritten on each run —
 * {@code jk idea} is idempotent and produces the same output for the same
 * lock. Files not generated by jk (e.g. {@code .idea/workspace.xml},
 * {@code vcs.xml}, hand-crafted run configs) are left untouched.
 */
public final class IdeaCommand implements CliCommand {

    @Override public String name()        { return "idea"; }
    @Override public String description() { return "Generate IntelliJ IDEA project files (.idea/ + *.iml)"; }

    @Override
    public List<Opt> options() {
        return List.of(
                Opt.value("<dir>", "Override the jk cache directory.", "--cache-dir").hide(),
                Opt.value("<dir>", "Override the JDK install root (for tests).", "--jdks-dir").hide(),
                Opt.value("<dir>", "Override the IDE config root for SDK registration (for tests).",
                        "--ide-config-dir").hide());
    }

    private GlobalOptions global;
    private Path cacheDir;

    @Override
    public int run(Invocation in) throws Exception {
        this.global    = GlobalOptions.from(in);
        this.cacheDir  = in.value("cache-dir").map(Path::of).orElse(null);

        Path startDir = global.workingDir();
        Path cache    = cacheDir != null ? cacheDir : JkDirs.cache();
        Cas  cas      = new Cas(cache);

        // Find workspace root (or treat single project as its own root).
        Path wsRoot;
        JkBuild rootBuild;
        try {
            Path buildFile = startDir.resolve("jk.toml");
            if (!Files.exists(buildFile)) {
                System.err.println("jk idea: no jk.toml in " + dev.jkbuild.cli.PathDisplay.styledRaw(startDir));
                return 2;
            }
            rootBuild = JkBuildParser.parse(buildFile);
            if (rootBuild.isWorkspaceRoot()) {
                wsRoot = startDir;
            } else {
                var rootOpt = WorkspaceLocator.findRoot(startDir);
                wsRoot = rootOpt.orElse(startDir);
                rootBuild = JkBuildParser.parse(wsRoot.resolve("jk.toml"));
            }
        } catch (RuntimeException e) {
            System.err.println("jk idea: " + e.getMessage());
            return 2;
        }
        // Canonicalize wsRoot so paths from BuildGraph (which calls toRealPath) and
        // workspace-loader paths are consistent — critical for correct relativize() on
        // systems where the temp/project dir is reached via a symlink (e.g. macOS
        // /var/folders → /private/var/folders).
        try { wsRoot = wsRoot.toRealPath(); } catch (java.io.IOException ignored) {}

        Map<Path, JkBuild> members = rootBuild.isWorkspaceRoot()
                ? WorkspaceLoader.loadMembers(wsRoot, rootBuild)
                : Map.of();

        // Unified module set: workspace members (or the single root) PLUS composite
        // (path / branch-git) dependency targets — each becomes an IDEA module so the
        // IDE resolves cross-project sources, not just compiled jars.
        Map<Path, JkBuild> allModules = new LinkedHashMap<>();
        if (members.isEmpty()) allModules.put(wsRoot, rootBuild);
        else allModules.putAll(members);
        allModules.putAll(resolveCompositeModules(wsRoot, rootBuild, cache));

        // Collect all library definitions across every module
        // (name → LibDef). LinkedHashMap preserves stable ordering.
        Map<String, LibDef> allLibs = new LinkedHashMap<>();
        for (Map.Entry<Path, JkBuild> me : allModules.entrySet()) {
            collectLibDefs(me.getKey(), me.getValue(), members, cas, allLibs);
        }

        // ---- generate .idea/ -----------------------------------------------
        Path ideaDir = wsRoot.resolve(".idea");
        Files.createDirectories(ideaDir);

        // Libraries are served from the repo directory (~/.jk/cache/repo/) which
        // stores hard-linked copies with proper Maven-layout filenames and .jar
        // extensions — IntelliJ can index them without any extra local linking.

        // ---- resolve per-module JDKs --------------------------------------
        // Each module maps to a stable jk-<vendor>-<level> SDK (e.g.
        // jk-temurin-25) backed by a StableJdkPointer path, so the generated
        // project resolves with no "missing SDK" and survives JDK point-release
        // upgrades. Modules at a different level get their own SDK + per-module
        // language level, instead of all inheriting the project default.
        Iterable<Map.Entry<Path, JkBuild>> targets = allModules.entrySet();

        Path jdksDirOverride   = in.value("jdks-dir").map(Path::of).orElse(null);
        Path ideConfigOverride = in.value("ide-config-dir").map(Path::of).orElse(null);
        JdkRegistry jdkRegistry = jdksDirOverride != null
                ? new JdkRegistry(jdksDirOverride) : new JdkRegistry();
        StableJdkPointer pointer = jdksDirOverride != null
                ? new StableJdkPointer(jdksDirOverride) : StableJdkPointer.atDefaultRoot();
        List<IntellijSdkRegistrar.SdkEntry> sdkEntries = new ArrayList<>();
        Set<String> seenSdk = new LinkedHashSet<>();
        Map<Path, SdkRef> sdkRefs = new LinkedHashMap<>();
        for (Map.Entry<Path, JkBuild> me : targets) {
            sdkRefs.put(me.getKey(),
                    sdkRefFor(me.getKey(), me.getValue(), jdkRegistry, pointer, sdkEntries, seenSdk));
        }
        SdkRef defaultSdk = defaultSdkRef(wsRoot, rootBuild, members, sdkRefs,
                jdkRegistry, pointer, sdkEntries, seenSdk);

        // Register the SDKs into every IntelliJ/Android Studio jdk.table.xml
        // (best-effort; may be clobbered if an IDE is open — see note below).
        IntellijSdkRegistrar registrar = ideConfigOverride != null
                ? IntellijSdkRegistrar.of(List.of(
                        ideConfigOverride.resolve("JetBrains"), ideConfigOverride.resolve("Google")))
                : IntellijSdkRegistrar.shared();
        List<Path> touchedTables = registrar.register(sdkEntries);

        // Annotation processors per module → routed to IntelliJ's annotation
        // processing config (not the compile classpath) and the generated
        // sources marked as a generated source root.
        Map<Path, List<Path>> processorJars = new LinkedHashMap<>();
        for (Map.Entry<Path, JkBuild> me : targets) {
            processorJars.put(me.getKey(),
                    processorLibFiles(me.getKey(), me.getValue(), members, allLibs));
        }

        int files = 0;
        files += writeModulesXml(ideaDir, wsRoot, allModules);
        files += writeMiscXml(ideaDir, defaultSdk);
        files += writeCompilerXml(ideaDir, wsRoot, allModules, processorJars);

        Path libsDir = ideaDir.resolve("libraries");
        Files.createDirectories(libsDir);
        for (LibDef lib : allLibs.values()) {
            write(libsDir.resolve(lib.fileName + ".xml"), libraryXml(lib));
            files++;
        }

        Path runDir = ideaDir.resolve("runConfigurations");
        for (Map.Entry<Path, JkBuild> me : members.entrySet()) {
            String main = me.getValue().project().main();
            if (main != null && !main.isBlank()) {
                Files.createDirectories(runDir);
                String modName = moduleName(me.getValue());
                write(runDir.resolve(sanitize(modName) + ".xml"),
                        runConfigXml(modName, main));
                files++;
            }
        }
        // Single-project run config
        if (members.isEmpty() && rootBuild.project().main() != null
                && !rootBuild.project().main().isBlank()) {
            Files.createDirectories(runDir);
            String modName = moduleName(rootBuild);
            write(runDir.resolve(sanitize(modName) + ".xml"),
                    runConfigXml(modName, rootBuild.project().main()));
            files++;
        }

        // ---- generate *.iml for each member --------------------------------
        for (Map.Entry<Path, JkBuild> me : targets) {
            Path memberDir = me.getKey();
            JkBuild member = me.getValue();
            List<ModuleRef> modRefs = new ArrayList<>(siblingModuleRefs(memberDir, member, members));
            modRefs.addAll(compositeModuleRefs(memberDir, member, cache));
            List<LibRef>    libRefs = libRefs(memberDir, member, members, cas, allLibs);
            write(memberDir.resolve(moduleName(member) + ".iml"),
                    imlXml(memberDir, member, modRefs, libRefs,
                            sdkRefs.get(memberDir), defaultSdk,
                            processorJars.getOrDefault(memberDir, List.of())));
            files++;
        }

        Theme t = Theme.active();
        String wsName = wsRoot.getFileName().toString();
        System.out.println(Theme.colorize("✓", t.success())
                + " Generated " + files + " project file" + (files == 1 ? "" : "s")
                + " in " + Theme.colorize(wsName + "/.idea", t.path()));
        if (!touchedTables.isEmpty()) {
            System.out.println("  Registered " + Theme.colorize(defaultSdk.sdkName(), t.cyan())
                    + " in " + touchedTables.size() + " IDE config"
                    + (touchedTables.size() == 1 ? "" : "s")
                    + ". Re-run the IDE if it doesn't appear.");
        }
        System.out.println(Theme.colorize("➜", t.brightGreen())
                + " The " + Theme.colorize(rootBuild.project().name(), t.brightCyan())
                + " project is ready to be opened in IntelliJ IDEA.");
        return 0;
    }

    // =========================================================================
    // JDK / SDK resolution
    // =========================================================================

    /**
     * Resolve a module's stable SDK handle. Prefers the module's locked JDK
     * identifier ({@code jk.lock}'s {@code jdk}, e.g. {@code temurin-25.0.3});
     * falls back to the declared {@code project.jdk} level and the default
     * vendor (Temurin). When the JDK is actually installed, ensures the
     * {@link StableJdkPointer} and queues an {@link IntellijSdkRegistrar.SdkEntry}
     * (once per distinct SDK).
     */
    private static SdkRef sdkRefFor(Path memberDir, JkBuild member,
                                    JdkRegistry registry, StableJdkPointer pointer,
                                    List<IntellijSdkRegistrar.SdkEntry> sdkEntries,
                                    Set<String> seen) throws IOException {
        int level = member.project().jdkMajor() > 0
                ? member.project().jdkMajor() : member.project().javaRelease();
        String lockJdk = readLockJdk(memberDir);
        JdkSelector.FlexibleQuery q =
                JdkSelector.parseFlexible(lockJdk == null ? "" : lockJdk);
        if (q.major().isPresent()) level = q.major().get();
        if (level <= 0) level = 21;

        Optional<JdkHit> hit = Optional.empty();
        if (lockJdk != null && !lockJdk.isBlank()) hit = registry.findHitBySpec(lockJdk);
        if (hit.isEmpty()) hit = registry.findHitBySpec(String.valueOf(level));

        String vendor;
        String version = q.exactVersion().orElse(null);
        if (hit.isPresent()) {
            JdkVendor v = hit.get().vendor();
            vendor = v.jbPrefix().orElse(v.vendor().toLowerCase(Locale.ROOT));
            if (version == null) version = hit.get().version();
        } else if (!q.hints().isEmpty()) {
            vendor = q.hints().get(0);
        } else {
            vendor = "temurin";
        }

        String stableName = vendor + "-" + level;
        String sdkName = "jk-" + stableName;
        if (hit.isPresent() && seen.add(sdkName)) {
            pointer.ensure(stableName, IntellijJdkDir.installDirOf(hit.get().home()));
            sdkEntries.add(new IntellijSdkRegistrar.SdkEntry(
                    sdkName, pointer.javaHome(stableName),
                    version != null ? version : String.valueOf(level)));
        }
        return new SdkRef(stableName, sdkName, member.project().javaRelease() > 0
                ? member.project().javaRelease() : level);
    }

    /**
     * The project-default SDK: mirrors the legacy rule (root {@code project.jdk},
     * else the highest member level). Reuses a member's resolved {@link SdkRef}
     * when one matches that level; otherwise resolves the root build itself.
     */
    private static SdkRef defaultSdkRef(Path wsRoot, JkBuild root, Map<Path, JkBuild> members,
                                        Map<Path, SdkRef> sdkRefs, JdkRegistry registry,
                                        StableJdkPointer pointer,
                                        List<IntellijSdkRegistrar.SdkEntry> sdkEntries,
                                        Set<String> seen) throws IOException {
        if (sdkRefs.containsKey(wsRoot)) return sdkRefs.get(wsRoot);
        int level = root.project().jdkMajor();
        if (level == 0) for (JkBuild m : members.values()) level = Math.max(level, m.project().jdkMajor());
        for (SdkRef r : sdkRefs.values()) if (r.languageLevel() == level) return r;
        return sdkRefFor(wsRoot, root, registry, pointer, sdkEntries, seen);
    }

    /** The resolved JDK identifier stamped in a member's {@code jk.lock}, or null. */
    private static String readLockJdk(Path memberDir) {
        Path lf = memberDir.resolve("jk.lock");
        if (!Files.exists(lf)) return null;
        try {
            return LockfileReader.read(lf).jdk();
        } catch (RuntimeException | IOException e) {
            return null;
        }
    }

    // =========================================================================
    // Library collection
    // =========================================================================

    /** Collect all external (non-workspace) dep library definitions for one member. */
    private static void collectLibDefs(Path memberDir, JkBuild member,
                                        Map<Path, JkBuild> members, Cas cas,
                                        Map<String, LibDef> allLibs) throws IOException {
        Path lockFile = memberDir.resolve("jk.lock");
        if (!Files.exists(lockFile)) return;
        Lockfile lock = LockfileReader.read(lockFile);

        // Fetch any missing JARs so the repo has entries to reference.
        // This mirrors `jk sync` — `jk idea` should work without a prior sync.
        try {
            new CacheSync(cas, new Http()).sync(lock, CacheSync.ProgressObserver.NOOP);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        } catch (Exception ignored) { /* best-effort; missing JARs are skipped below */ }

        // Build a set of workspace-sibling coordinates so we can skip them.
        Set<String> siblingCoords = siblingCoordinates(member, members);
        JkMavenLocalRepo repo = new JkMavenLocalRepo(cas.root());

        for (Lockfile.Artifact pkg : lock.artifacts()) {
            if (pkg.checksum() == null) continue;            // path/git dep
            if (siblingCoords.contains(pkg.name())) continue; // workspace sibling → module dep
            if (allLibs.containsKey(pkg.name() + ":" + pkg.version())) continue;

            int colon = pkg.name().indexOf(':');
            if (colon < 0) continue;
            Coordinate coord = Coordinate.of(
                    pkg.name().substring(0, colon),
                    pkg.name().substring(colon + 1),
                    pkg.version());

            // Use the repo (Maven-layout with proper .jar extension) rather than
            // the CAS (extension-less hash paths). IntelliJ requires .jar extension.
            String artifactRelPath = MavenLayout.artifactPath(coord);
            Optional<Path> jarOpt = repo.locate(artifactRelPath);
            if (jarOpt.isEmpty()) {
                // CAS has the blob but jk sync pre-dated the repo mirror — materialize now.
                String hex = hexOf(pkg.checksum());
                if (hex != null && cas.contains(hex)) {
                    repo.materialize(artifactRelPath, cas.pathFor(hex));
                    jarOpt = repo.locate(artifactRelPath);
                }
            }
            if (jarOpt.isEmpty()) continue; // not yet synced / non-Maven dep

            Path sourcesPath = null;
            if (pkg.sourcesChecksum() != null) {
                Coordinate srcCoord = new Coordinate(
                        coord.group(), coord.artifact(), coord.version(), "sources", "jar");
                String srcRelPath = MavenLayout.artifactPath(srcCoord);
                sourcesPath = repo.locate(srcRelPath).orElse(null);
                if (sourcesPath == null) {
                    String srcHex = hexOf(pkg.sourcesChecksum());
                    if (srcHex != null && cas.contains(srcHex)) {
                        repo.materialize(srcRelPath, cas.pathFor(srcHex));
                        sourcesPath = repo.locate(srcRelPath).orElse(null);
                    }
                }
            }

            String libName = pkg.name() + ":" + pkg.version();
            allLibs.put(libName, new LibDef(libName, libFileName(libName),
                    jarOpt.get(), sourcesPath));
        }
    }

    // =========================================================================
    // Composite (path / branch-git) dependency modules
    // =========================================================================

    /**
     * Every composite ({@code path} / branch-git) dependency target across the
     * whole graph, as an IDEA module ({@code dir → manifest}). Best-effort: on a
     * resolution error the IDE is still generated for the workspace, just without
     * composite modules.
     */
    private Map<Path, JkBuild> resolveCompositeModules(Path wsRoot, JkBuild rootBuild, Path cache) {
        Map<Path, JkBuild> out = new LinkedHashMap<>();
        try {
            BuildGraph.Result g = BuildGraph.resolve(wsRoot, rootBuild, cache.resolve("git"));
            if (g.hasErrors()) {
                for (String e : g.errors()) System.err.println("jk idea: " + e);
                return out;
            }
            for (BuildGraph.BuildUnit u : g.topoOrder()) {
                if (u.isDependency()) out.put(u.dir(), u.manifest());
            }
        } catch (Exception e) {
            System.err.println("jk idea: composite dependencies skipped (" + e.getMessage() + ")");
        }
        return out;
    }

    /**
     * Module references for a project's direct composite deps — each resolves to
     * the target's IDEA module (by name), so the consumer module depends on the
     * composite target's sources (jk's includeBuild, in the IDE).
     */
    private static List<ModuleRef> compositeModuleRefs(Path dir, JkBuild project, Path cache) {
        List<ModuleRef> refs = new ArrayList<>();
        Set<String> seen = new LinkedHashSet<>();
        for (Scope scope : Scope.values()) {
            for (Dependency d : project.dependencies().of(scope)) {
                boolean composite = d.isPath()
                        || (d.isGit() && !d.gitSource().ref().isImmutable());
                if (!composite) continue;
                try {
                    Path toml = BuildGraph.targetDir(dir, d, cache.resolve("git")).resolve("jk.toml");
                    if (!Files.isRegularFile(toml)) continue;
                    String name = moduleName(JkBuildParser.parse(toml));
                    if (seen.add(name)) {
                        refs.add(new ModuleRef(name, scope == Scope.TEST ? "TEST" : "COMPILE"));
                    }
                } catch (Exception ignored) {
                    // Unresolved composite (e.g. offline branch dep) — skip the ref.
                }
            }
        }
        return refs;
    }

    // =========================================================================
    // Per-module dependency lists
    // =========================================================================

    /** Workspace siblings this module directly depends on (MAIN + TEST scopes). */
    private static List<ModuleRef> siblingModuleRefs(Path memberDir, JkBuild member,
                                                      Map<Path, JkBuild> members)
            throws IOException {
        List<ModuleRef> result = new ArrayList<>();
        WorkspaceClasspath.Result mainCp =
                WorkspaceClasspath.resolve(memberDir, member, EnumSet.of(Scope.EXPORT, Scope.MAIN));
        WorkspaceClasspath.Result testCp =
                WorkspaceClasspath.resolve(memberDir, member, EnumSet.of(Scope.TEST));

        // Map jar → module name for all workspace siblings
        Map<Path, String> jarToModule = new LinkedHashMap<>();
        for (Map.Entry<Path, JkBuild> me : members.entrySet()) {
            BuildLayout layout = BuildLayout.of(me.getKey(), me.getValue());
            jarToModule.put(layout.mainJar(), moduleName(me.getValue()));
        }

        // Use the full declared closure, not jars() — the latter is filtered to
        // jars that already exist on disk, so before a first build every sibling
        // dependency would be dropped and IntelliJ couldn't resolve any
        // cross-module classes. IntelliJ compiles the modules itself; the edge
        // is what matters, not the artifact.
        Set<String> added = new LinkedHashSet<>();
        for (Path sj : mainCp.siblingClosureJars()) {
            String name = jarToModule.get(sj);
            if (name != null && added.add(name))
                result.add(new ModuleRef(name, "COMPILE"));
        }
        for (Path sj : testCp.siblingClosureJars()) {
            String name = jarToModule.get(sj);
            if (name != null && added.add(name))
                result.add(new ModuleRef(name, "TEST"));
        }
        return result;
    }

    /** External library references (scope-tagged) for one module. */
    private static List<LibRef> libRefs(Path memberDir, JkBuild member,
                                         Map<Path, JkBuild> allMembers, Cas cas,
                                         Map<String, LibDef> allLibs) throws IOException {
        Path lockFile = memberDir.resolve("jk.lock");
        if (!Files.exists(lockFile)) return List.of();
        Lockfile lock = LockfileReader.read(lockFile);
        Set<String> siblingCoords = siblingCoordinates(member, allMembers);

        List<LibRef> result = new ArrayList<>();
        for (Lockfile.Artifact pkg : lock.artifacts()) {
            if (pkg.checksum() == null) continue;
            if (siblingCoords.contains(pkg.name())) continue;
            // Processor-only deps belong on the annotation-processor path
            // (compiler.xml), not the compile classpath.
            if (processorOnly(pkg.scopes())) continue;
            String libName = pkg.name() + ":" + pkg.version();
            if (!allLibs.containsKey(libName)) continue;
            result.add(new LibRef(libName, ideaScope(pkg.scopes())));
        }
        return result;
    }

    /**
     * The {@code .idea/.libs} file names (no extension) of a member's
     * processor-scoped deps — fed into the module's annotation-processing
     * profile. The JARs are already linked by {@link #collectLibDefs}.
     */
    private static List<Path> processorLibFiles(Path memberDir, JkBuild member,
                                                 Map<Path, JkBuild> members,
                                                 Map<String, LibDef> allLibs) throws IOException {
        Path lockFile = memberDir.resolve("jk.lock");
        if (!Files.exists(lockFile)) return List.of();
        Lockfile lock = LockfileReader.read(lockFile);
        Set<String> siblingCoords = siblingCoordinates(member, members);
        List<Path> out = new ArrayList<>();
        for (Lockfile.Artifact pkg : lock.artifacts()) {
            if (pkg.checksum() == null) continue;
            if (siblingCoords.contains(pkg.name())) continue;
            if (!pkg.inAnyScope(EnumSet.of(Scope.PROCESSOR))) continue;
            LibDef def = allLibs.get(pkg.name() + ":" + pkg.version());
            if (def != null && def.jarPath() != null) out.add(def.jarPath());
        }
        return out;
    }

    /** True when {@code PROCESSOR} is the only classpath-relevant scope on a package. */
    private static boolean processorOnly(List<Scope> scopes) {
        if (!scopes.contains(Scope.PROCESSOR)) return false;
        for (Scope s : scopes) {
            if (s == Scope.MAIN || s == Scope.EXPORT || s == Scope.PROVIDED
                    || s == Scope.RUNTIME || s == Scope.TEST) {
                return false;
            }
        }
        return true;
    }

    // =========================================================================
    // XML generators
    // =========================================================================

    private static int writeModulesXml(Path ideaDir, Path wsRoot,
                                        Map<Path, JkBuild> modules)
            throws IOException {
        StringBuilder sb = xmlHeader();
        sb.append("<project version=\"4\">\n");
        sb.append("  <component name=\"ProjectModuleManager\">\n");
        sb.append("    <modules>\n");

        for (Map.Entry<Path, JkBuild> me : modules.entrySet()) {
            Path iml = me.getKey().resolve(moduleName(me.getValue()) + ".iml");
            String rel = "$PROJECT_DIR$/" + wsRoot.relativize(iml).toString().replace('\\', '/');
            sb.append("      <module fileurl=\"file://").append(rel)
              .append("\" filepath=\"").append(rel).append("\" />\n");
        }
        sb.append("    </modules>\n  </component>\n</project>\n");
        write(ideaDir.resolve("modules.xml"), sb.toString());
        return 1;
    }

    private static int writeMiscXml(Path ideaDir, SdkRef defaultSdk) throws IOException {
        StringBuilder sb = xmlHeader();
        sb.append("<project version=\"4\">\n");
        sb.append("  <component name=\"ProjectRootManager\" version=\"2\"");
        sb.append(" languageLevel=\"JDK_").append(defaultSdk.languageLevel()).append("\"");
        sb.append(" project-jdk-name=\"").append(esc(defaultSdk.sdkName())).append("\"");
        sb.append(" project-jdk-type=\"JavaSDK\">\n");
        sb.append("    <output url=\"file://$PROJECT_DIR$/out\" />\n");
        sb.append("  </component>\n</project>\n");
        write(ideaDir.resolve("misc.xml"), sb.toString());
        return 1;
    }

    private static int writeCompilerXml(Path ideaDir, Path wsRoot,
                                         Map<Path, JkBuild> modules,
                                         Map<Path, List<Path>> processorJars)
            throws IOException {
        StringBuilder sb = xmlHeader();
        sb.append("<project version=\"4\">\n");
        sb.append("  <component name=\"CompilerConfiguration\">\n");
        sb.append("    <bytecodeTargetLevel>\n");

        Iterable<Map.Entry<Path, JkBuild>> targets = modules.entrySet();

        for (Map.Entry<Path, JkBuild> me : targets) {
            int release = me.getValue().project().javaRelease();
            if (release > 0) {
                sb.append("      <module name=\"").append(esc(moduleName(me.getValue())))
                  .append("\" targetLevel=\"").append(release).append("\" />\n");
            }
        }
        sb.append("    </bytecodeTargetLevel>\n");

        // Annotation processing: one profile per module that declares
        // processor-scoped deps. Each binds the module, its processor JARs (from
        // the Maven-layout repo with proper .jar extension), and the generated-
        // sources output dir so IntelliJ runs the processors the same way jk does.
        boolean anyProcessors = processorJars.values().stream().anyMatch(l -> !l.isEmpty());
        if (anyProcessors) {
            sb.append("    <annotationProcessing>\n");
            for (Map.Entry<Path, JkBuild> me : targets) {
                List<Path> procs = processorJars.getOrDefault(me.getKey(), List.of());
                if (procs.isEmpty()) continue;
                String mod = moduleName(me.getValue());
                BuildLayout layout = BuildLayout.of(me.getKey(), me.getValue());
                String genRel = me.getKey().relativize(layout.generatedSourcesDir("annotations"))
                        .toString().replace('\\', '/');
                sb.append("      <profile name=\"jk-").append(esc(mod)).append("\" enabled=\"true\">\n");
                sb.append("        <sourceOutputDir name=\"").append(esc(genRel)).append("\" />\n");
                sb.append("        <outputRelativeToContentRoot value=\"true\" />\n");
                sb.append("        <module name=\"").append(esc(mod)).append("\" />\n");
                sb.append("        <processorPath useClasspath=\"false\">\n");
                for (Path jar : procs) {
                    sb.append("          <entry name=\"").append(repoJarUrl(jar)).append("\" />\n");
                }
                sb.append("        </processorPath>\n");
                sb.append("      </profile>\n");
            }
            sb.append("    </annotationProcessing>\n");
        }

        sb.append("  </component>\n</project>\n");
        write(ideaDir.resolve("compiler.xml"), sb.toString());
        return 1;
    }

    private static String libraryXml(LibDef lib) {
        StringBuilder sb = xmlHeader();
        sb.append("<component name=\"libraryTable\">\n");
        sb.append("  <library name=\"").append(esc(lib.name)).append("\">\n");
        sb.append("    <CLASSES>\n");
        sb.append("      <root url=\"").append(repoJarUrl(lib.jarPath)).append("\" />\n");
        sb.append("    </CLASSES>\n");
        sb.append("    <JAVADOC />\n");
        sb.append("    <SOURCES>\n");
        if (lib.sourcesPath != null) {
            sb.append("      <root url=\"").append(repoJarUrl(lib.sourcesPath)).append("\" />\n");
        }
        sb.append("    </SOURCES>\n");
        sb.append("  </library>\n</component>\n");
        return sb.toString();
    }

    private static String imlXml(Path memberDir, JkBuild member,
                                   List<ModuleRef> modRefs, List<LibRef> libRefs,
                                   SdkRef memberSdk, SdkRef defaultSdk,
                                   List<Path> processorFiles) {
        boolean ownJdk = memberSdk != null && defaultSdk != null
                && !memberSdk.sdkName().equals(defaultSdk.sdkName());
        int langLevel = memberSdk != null ? memberSdk.languageLevel() : 0;

        StringBuilder sb = xmlHeader();
        sb.append("<module type=\"JAVA_MODULE\" version=\"4\">\n");
        sb.append("  <component name=\"NewModuleRootManager\" inherit-compiler-output=\"false\"");
        // Per-module source language level when this module differs from the
        // project default (e.g. a jdk=21 member under a jdk=25 root).
        if (ownJdk && langLevel > 0) {
            sb.append(" LANGUAGE_LEVEL=\"JDK_").append(langLevel).append("\"");
        }
        sb.append(">\n");

        BuildLayout layout = BuildLayout.of(memberDir, member);
        sb.append("    <output url=\"file://$MODULE_DIR$/")
          .append(memberDir.relativize(layout.classesDir()).toString().replace('\\', '/'))
          .append("\" />\n");
        sb.append("    <output-test url=\"file://$MODULE_DIR$/")
          .append(memberDir.relativize(layout.testClassesDir()).toString().replace('\\', '/'))
          .append("\" />\n");
        sb.append("    <exclude-output />\n");

        // Source / test / resource folders.
        // Traditional layout (Maven convention) takes precedence over simple layout:
        // only add "src" / "test" if no traditional source dirs exist.
        sb.append("    <content url=\"file://$MODULE_DIR$\">\n");
        boolean hasTraditional =
                Files.isDirectory(memberDir.resolve("src/main/java")) ||
                Files.isDirectory(memberDir.resolve("src/main/kotlin")) ||
                Files.isDirectory(memberDir.resolve("src/test/java"))  ||
                Files.isDirectory(memberDir.resolve("src/test/kotlin"));
        if (hasTraditional) {
            addSourceFolder(sb, memberDir, "src/main/java",      false);
            addSourceFolder(sb, memberDir, "src/main/kotlin",    false);
            addResourceFolder(sb, memberDir, "src/main/resources", false);
            addSourceFolder(sb, memberDir, "src/test/java",      true);
            addSourceFolder(sb, memberDir, "src/test/kotlin",    true);
            addResourceFolder(sb, memberDir, "src/test/resources", true);
        } else {
            // simple layout
            addSourceFolder(sb, memberDir, "src",            false);
            addResourceFolder(sb, memberDir, "resources",      false);
            addSourceFolder(sb, memberDir, "test",           true);
            addResourceFolder(sb, memberDir, "test-resources", true);
        }

        // Annotation-processor output → a generated source root. Declared even
        // when it doesn't exist yet (processors run on first build) so the
        // editor recognises the generated code. An explicit source root nested
        // under the `target` exclude below still wins — the Maven/Gradle
        // importers rely on the same precedence.
        Path gen = layout.generatedSourcesDir("annotations");
        if (!processorFiles.isEmpty() || Files.isDirectory(gen)) {
            String genRel = memberDir.relativize(gen).toString().replace('\\', '/');
            sb.append("      <sourceFolder url=\"file://$MODULE_DIR$/").append(genRel)
              .append("\" isTestSource=\"false\" generated=\"true\" />\n");
        }

        // exclude build outputs
        sb.append("      <excludeFolder url=\"file://$MODULE_DIR$/target\" />\n");
        sb.append("    </content>\n");

        // JDK: a dedicated SDK when this module's level differs from the project
        // default; otherwise inherit the project SDK.
        if (ownJdk) {
            sb.append("    <orderEntry type=\"jdk\" jdkName=\"").append(esc(memberSdk.sdkName()))
              .append("\" jdkType=\"JavaSDK\" />\n");
        } else {
            sb.append("    <orderEntry type=\"inheritedJdk\" />\n");
        }
        sb.append("    <orderEntry type=\"sourceFolder\" forTests=\"false\" />\n");

        // Workspace-sibling module dependencies
        for (ModuleRef mr : modRefs) {
            sb.append("    <orderEntry type=\"module\" module-name=\"")
              .append(esc(mr.name)).append("\"");
            if ("TEST".equals(mr.scope)) sb.append(" scope=\"TEST\"");
            sb.append(" />\n");
        }

        // External library references
        for (LibRef lr : libRefs) {
            sb.append("    <orderEntry type=\"library\" name=\"")
              .append(esc(lr.name)).append("\" level=\"project\"");
            if (!"COMPILE".equals(lr.scope))
                sb.append(" scope=\"").append(lr.scope).append("\"");
            sb.append(" />\n");
        }

        sb.append("  </component>\n</module>\n");
        return sb.toString();
    }

    private static String runConfigXml(String moduleName, String mainClass) {
        StringBuilder sb = xmlHeader();
        sb.append("<component name=\"ProjectRunConfigurationManager\">\n");
        sb.append("  <configuration default=\"false\" name=\"")
          .append(esc(moduleName)).append("\" type=\"Application\" factoryName=\"Application\">\n");
        sb.append("    <option name=\"MAIN_CLASS_NAME\" value=\"")
          .append(esc(mainClass)).append("\" />\n");
        sb.append("    <module name=\"").append(esc(moduleName)).append("\" />\n");
        sb.append("    <method v=\"2\">\n");
        sb.append("      <option name=\"Make\" enabled=\"true\" />\n");
        sb.append("    </method>\n");
        sb.append("  </configuration>\n</component>\n");
        return sb.toString();
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    private static void addSourceFolder(StringBuilder sb, Path memberDir,
                                         String relative, boolean test) {
        Path dir = memberDir.resolve(relative);
        if (!Files.isDirectory(dir)) return;
        sb.append("      <sourceFolder url=\"file://$MODULE_DIR$/")
          .append(relative).append("\" isTestSource=\"").append(test).append("\" />\n");
    }

    /** A resource root ({@code java-resource} / {@code java-test-resource}), only when present. */
    private static void addResourceFolder(StringBuilder sb, Path memberDir,
                                          String relative, boolean test) {
        Path dir = memberDir.resolve(relative);
        if (!Files.isDirectory(dir)) return;
        sb.append("      <sourceFolder url=\"file://$MODULE_DIR$/")
          .append(relative).append("\" type=\"")
          .append(test ? "java-test-resource" : "java-resource").append("\" />\n");
    }

    /** The IntelliJ module name for a workspace member. */
    private static String moduleName(JkBuild member) {
        return member.project().name();
    }

    /** Sanitize a string to a valid filename component. */
    private static String sanitize(String s) {
        return s.replaceAll("[^A-Za-z0-9._-]", "_");
    }

    /** Library filename (no extension). Replaces non-safe chars with underscores. */
    private static String libFileName(String libName) {
        return sanitize(libName.replace(':', '_').replace('.', '_'));
    }

    /**
     * Convert a JAR path to IntelliJ's {@code jar://...!/} URL format.
     * Paths inside the workspace use {@code $PROJECT_DIR$} (portable);
     * other paths fall back to {@code $USER_HOME$}-relative or absolute.
     */
    /**
     * Convert a repo JAR path to IntelliJ's {@code jar://...!/} URL format.
     * Repo files live under {@code ~/.jk/cache/repo/} and use {@code $USER_HOME$}.
     */
    private static String repoJarUrl(Path jar) {
        String absStr = jar.toAbsolutePath().normalize().toString().replace('\\', '/');
        String home = System.getProperty("user.home", "").replace('\\', '/');
        if (!home.isBlank() && absStr.startsWith(home + "/")) {
            absStr = "$USER_HOME$/" + absStr.substring(home.length() + 1);
        }
        return "jar://" + absStr + "!/";
    }

    /** Extract the raw hex SHA from a {@code "sha256:<hex>"} checksum string. */
    private static String hexOf(String checksum) {
        if (checksum == null) return null;
        return checksum.startsWith("sha256:") ? checksum.substring(7) : checksum;
    }

    /** Map jk scopes to the most permissive IntelliJ scope. */
    private static String ideaScope(List<dev.jkbuild.model.Scope> scopes) {
        Set<dev.jkbuild.model.Scope> s = EnumSet.noneOf(dev.jkbuild.model.Scope.class);
        s.addAll(scopes);
        if (s.contains(Scope.EXPORT) || s.contains(Scope.MAIN)) return "COMPILE";
        if (s.contains(Scope.PROVIDED))                          return "PROVIDED";
        if (s.contains(Scope.RUNTIME))                          return "RUNTIME";
        if (s.contains(Scope.TEST))                             return "TEST";
        return "COMPILE";
    }

    /** Coordinates of all workspace siblings that this member could declare as deps. */
    private static Set<String> siblingCoordinates(JkBuild member,
                                                    Map<Path, JkBuild> allMembers) {
        Set<String> coords = new LinkedHashSet<>();
        for (JkBuild sib : allMembers.values()) {
            if (sib != member) {
                coords.add(sib.project().group() + ":" + sib.project().name());
            }
        }
        return coords;
    }

    private static StringBuilder xmlHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
        return sb;
    }

    /** XML-escape a string for attribute values. */
    private static String esc(String s) {
        return s.replace("&", "&amp;").replace("\"", "&quot;")
                .replace("<", "&lt;").replace(">", "&gt;");
    }

    private static void write(Path file, String content) throws IOException {
        Files.writeString(file, content, StandardCharsets.UTF_8);
    }

    // =========================================================================
    // Data records
    // =========================================================================

    /**
     * @param jarPath     repo path with proper .jar extension (e.g. ~/.jk/cache/repo/.../lib-1.0.jar)
     * @param sourcesPath repo path for the -sources.jar (may be null)
     */
    private record LibDef(String name, String fileName, Path jarPath, Path sourcesPath) {}

    private record LibRef(String name, String scope) {}
    private record ModuleRef(String name, String scope) {}

    /**
     * A module's resolved JDK handle.
     *
     * @param stableName    the {@code <vendor>-<level>} pointer name (e.g. {@code temurin-25})
     * @param sdkName       the IntelliJ SDK name (e.g. {@code jk-temurin-25})
     * @param languageLevel the source language level for this module ({@code project.java}/{@code jdk})
     */
    private record SdkRef(String stableName, String sdkName, int languageLevel) {}
}
