[project]
group    = "dev.jkbuild"
artifact = "jk-compat"
version  = "0.6.0-SNAPSHOT"
jdk      = 25
java     = 25

[dependencies.main]
jk-core.workspace = true
jk-io.workspace   = true
commons-compress  = { group = "org.apache.commons", version = "1.28.0" }

[dependencies.test]
assertj-core.workspace            = true
junit-jupiter.workspace           = true
junit-platform-launcher.workspace = true
