[project]
group    = "dev.jkbuild"
artifact = "jk-compat"
version  = "0.6.0-SNAPSHOT"
jdk      = 25
java     = 25

[dependencies]
main = [
  "dev.jkbuild:jk-core:0.6.0-SNAPSHOT",
  "dev.jkbuild:jk-io:0.6.0-SNAPSHOT",
  "org.apache.commons:commons-compress:1.28.0",
]
test = [
  "org.assertj:assertj-core:3.27.7",
  "org.junit.jupiter:junit-jupiter:6.1.0",
  "org.junit.platform:junit-platform-launcher:6.1.0",
]
