[project]
group    = "dev.jkbuild"
artifact = "jk-cli"
version  = "0.6.0-SNAPSHOT"
jdk      = "25"
language = "java"
main     = "dev.jkbuild.cli.Jk"

[dependencies]
main = [
  "dev.jkbuild:jk-compat:0.6.0-SNAPSHOT",
  "dev.jkbuild:jk-core:0.6.0-SNAPSHOT",
  "dev.jkbuild:jk-engine:0.6.0-SNAPSHOT",
  "dev.jkbuild:jk-image:0.6.0-SNAPSHOT",
  "dev.jkbuild:jk-io:0.6.0-SNAPSHOT",
  "dev.jkbuild:jk-resolver:0.6.0-SNAPSHOT",
  "dev.jkbuild:jk-supply-chain:0.6.0-SNAPSHOT",
  "dev.jkbuild:jk-toolchain:0.6.0-SNAPSHOT",
  "info.picocli:picocli:4.7.7",
]
test = [
  "org.assertj:assertj-core:3.27.7",
  "org.junit.jupiter:junit-jupiter:6.1.0",
  "org.junit.platform:junit-platform-launcher:6.1.0",
]

[image]
main-class = "dev.jkbuild.cli.Jk"
