[project]
group    = "dev.jkbuild"
artifact = "jk-cli"
version  = "0.6.0-SNAPSHOT"
jdk      = 25
java     = 25
main     = "dev.jkbuild.cli.Jk"

[dependencies.main]
jk-compat.workspace       = true
jk-core.workspace         = true
jk-engine.workspace       = true
jk-image.workspace        = true
jk-io.workspace           = true
jk-resolver.workspace     = true
jk-supply-chain.workspace = true
jk-toolchain.workspace    = true
picocli                   = { group = "info.picocli", version = "4.7.7" }

[dependencies.test]
assertj-core.workspace            = true
junit-jupiter.workspace           = true
junit-platform-launcher.workspace = true

[image]
main-class = "dev.jkbuild.cli.Jk"
