[project]
group    = "dev.jkbuild"
artifact = "jk-core"
version  = "0.6.0-SNAPSHOT"
jdk      = 25
java     = 25

[dependencies.main]
typesafe-config            = { group = "com.typesafe", artifact = "config", version = "1.4.8" }
tomlj                      = "1.1.1"   # registry → org.tomlj:tomlj
jackson-databind.workspace = true

[dependencies.test]
assertj-core.workspace            = true
junit-jupiter.workspace           = true
junit-platform-launcher.workspace = true
