[project]
group    = "dev.jkbuild"
artifact = "jk-supply-chain"
version  = "0.6.0-SNAPSHOT"
jdk      = 25
java     = 25

[dependencies.main]
jk-core.workspace          = true
jk-io.workspace            = true
sigstore-java              = { group = "dev.sigstore",     version = "2.1.0" }
bcpg-jdk18on               = { group = "org.bouncycastle", version = "1.84" }
cyclonedx-core-java        = { group = "org.cyclonedx",    version = "12.2.0" }
java-spdx-library          = { group = "org.spdx",         version = "2.0.3" }
jackson-databind.workspace = true

[dependencies.test]
assertj-core.workspace            = true
junit-jupiter.workspace           = true
junit-platform-launcher.workspace = true
