[project]
group    = "dev.jkbuild"
artifact = "jk-resolver"
version  = "0.6.0-SNAPSHOT"
jdk      = "25"
language = "java"

[dependencies]
main = [
  "dev.jkbuild:jk-core:0.6.0-SNAPSHOT",
  "dev.jkbuild:jk-io:0.6.0-SNAPSHOT",
]
test = [
  "org.assertj:assertj-core:3.27.7",
  "org.junit.jupiter:junit-jupiter:6.1.0",
  "org.junit.platform:junit-platform-launcher:6.1.0",
]
