[project]
group    = "dev.jkbuild"
artifact = "jk-resolver"
version  = "0.6.0-SNAPSHOT"
jdk      = 25
java     = 25

[dependencies.main]
jk-core.workspace = true
jk-io.workspace   = true

[dependencies.test]
assertj-core.workspace            = true
junit-jupiter.workspace           = true
junit-platform-launcher.workspace = true
