// SPDX-License-Identifier: Apache-2.0
package dev.jkbuild.android;

import dev.jkbuild.plugin.build.StepExec;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * The {@code android-buildconfig} step ({@code [android] build-config = true} — an explicit
 * toggle, deliberately not AGP's default-on grab-bag): a generated {@code BuildConfig.java}
 * under the module's namespace, contributed to the compiler's source set. {@code DEBUG} is true
 * until release variants land (android-plan Phase 3 wires build types through here).
 */
final class BuildConfigStep {

    private BuildConfigStep() {}

    static void run(StepExec exec) throws Exception {
        String namespace = exec.config().string("namespace");
        Path gen = exec.outputDir("gen");
        Path file = gen.resolve(namespace.replace('.', '/')).resolve("BuildConfig.java");
        Files.createDirectories(file.getParent());
        exec.label("BuildConfig");
        Files.writeString(
                file,
                "/* Generated by jk — do not edit. */\n"
                        + "package " + namespace + ";\n\n"
                        + "public final class BuildConfig {\n"
                        + "    private BuildConfig() {}\n\n"
                        + "    public static final boolean DEBUG = true;\n"
                        + "    public static final String APPLICATION_ID = \"" + namespace + "\";\n"
                        + "    public static final String VERSION_NAME = \"" + exec.project().version() + "\";\n"
                        + "    public static final int VERSION_CODE = 1;\n"
                        + "}\n");
    }
}
