#!/bin/sh
# jk wrapper — generated by `jk wrapper`; do not edit (regenerate instead).
#
# Dumb and frozen by design (docs/engine-versioning-plan.md §7): read the exact pin from
# jk.lock, materialize that client under ~/.jk/versions/<v>/ if missing (sha-verified
# against the PIN), exec it. Never resolves version selectors; never updates itself —
# `jk wrapper --version <v|latest>` springboards through whatever client answers.
set -eu

JK_HOME="${JK_HOME:-$HOME/.jk}"
RELEASES="${JK_RELEASES_URL:-https://jkbuild.dev/releases}"
DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

VERSION=""
SHA=""
if [ -f "$DIR/jk.lock" ]; then
  LINE="$(grep '^jk = ' "$DIR/jk.lock" 2>/dev/null || true)"
  VERSION="$(printf '%s' "$LINE" | sed -n 's/.*version = "\([^"]*\)".*/\1/p')"
  SHA="$(printf '%s' "$LINE" | sed -n 's/.*sha256 = "\([^"]*\)".*/\1/p')"
fi
if [ -z "$VERSION" ]; then
  # No lock yet: bootstrap the latest release; the real client resolves and locks.
  VERSION="$(curl -fsSL "$RELEASES/latest/VERSION" | tr -d '[:space:]')"
fi

BIN="$JK_HOME/versions/$VERSION/bin/jk"
if [ ! -x "$BIN" ]; then
  OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
  case "$OS" in darwin) OS=macos ;; esac
  ARCH="$(uname -m)"
  case "$ARCH" in amd64) ARCH=x86_64 ;; arm64) ARCH=aarch64 ;; esac
  URL="$RELEASES/$VERSION/jk-$OS-$ARCH.zip"
  TMP="$(mktemp -d)"
  trap 'rm -rf "$TMP"' EXIT
  echo "jk wrapper: fetching jk $VERSION ..." >&2
  curl -fsSL -o "$TMP/jk.zip" "$URL"
  (cd "$TMP" && unzip -q jk.zip)
  # The release zip carries exactly one file (the client binary); anchor on the expected
  # names first so an unexpected extra entry can never be executed.
  CLIENT="$(find "$TMP" -type f \( -name jk -o -name 'jk-*' \) ! -name jk.zip | head -1)"
  [ -n "$CLIENT" ] || CLIENT="$(find "$TMP" -type f ! -name jk.zip | head -1)"
  if [ -n "$SHA" ]; then
    GOT="$( (sha256sum "$CLIENT" 2>/dev/null || shasum -a 256 "$CLIENT") | awk '{print $1}')"
    if [ "$GOT" != "$SHA" ]; then
      echo "jk wrapper: sha256 mismatch for jk $VERSION — refusing (expected $SHA, got $GOT)" >&2
      exit 1
    fi
  fi
  mkdir -p "$JK_HOME/versions/$VERSION/bin"
  cp "$CLIENT" "$BIN.part" && chmod +x "$BIN.part" && mv "$BIN.part" "$BIN"
fi

exec "$BIN" "$@"
