[project]
group    = "dev.jkbuild"
artifact = "jk-image"
version  = "0.6.0-SNAPSHOT"
jdk      = 25
java     = 25

[dependencies.main]
jib-core          = { group = "com.google.cloud.tools", version = "0.28.1" }
jk-core.workspace = true
jk-io.workspace   = true

[dependencies.test]
assertj-core.workspace            = true
junit-jupiter.workspace           = true
junit-platform-launcher.workspace = true
